# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */
pref("network.dns.blockDotOnion", false);
pref("network.proxy.autoconfig_url", "file:///etc/anonsurf/onion.pac");
pref("network.proxy.socks", "127.0.0.1");
pref("network.proxy.socks_port", 9050);
pref("network.proxy.type", 2);
pref("extensions.update.enabled", true);
pref("intl.locale.matchOS", true);
pref("browser.shell.checkDefaultBrowser", false);
pref("media.gmp-manager.url.override", "data:text/plain,");
pref("media.gmp-gmpopenh264.enabled", false);
pref("datareporting.healthreport.uploadEnabled", false);
pref("browser.search.defaultenginename", "DuckDuckGo");
pref("capability.policy.maonoscript.sites", "parrotsec.org cloudflare.com frozenbox.org duckduckgo.com about: about:addons about:blank about:blocked about:certerror about:config about:crashes about:home about:memory about:neterror about:plugins about:preferences about:privatebrowsing about:sessionrestore about:srcdoc about:support blob: chrome: http://cloudflare.com http://frozenbox.org http://parrotsec.org http://duckduckgo.com https://cloudflare.com https://frozenbox.org https://parrotsec.org https://duckduckgo.com mediasource: moz-extension: moz-safe-about: resource:");
