# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("network.dns.blockDotOnion", false);
user_pref("browser.startup.homepage","https://start.parrotsec.org");
user_pref("accessibility.blockautorefresh", true);
user_pref("accessibility.browsewithcaret", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1469395111142");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1469396911142");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1469395059332");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1469398659332");
user_pref("browser.search.countryCode", "IT");
user_pref("browser.search.defaultenginename", "DuckDuckGo");
user_pref("browser.search.hiddenOneOffs", "Bing,Amazon.com,eBay,Twitter");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"useragentoverrider-button\",\"https-everywhere-button\",\"noscript-tbb\",\"wot-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"web-developer-toolbar\":[\"web-developer-disable-toolbar\",\"web-developer-cookies-toolbar\",\"web-developer-css-toolbar\",\"web-developer-forms-toolbar\",\"web-developer-images-toolbar\",\"web-developer-information-toolbar\",\"web-developer-miscellaneous-toolbar\",\"web-developer-outline-toolbar\",\"web-developer-resize-toolbar\",\"web-developer-tools-toolbar\",\"web-developer-view-source-toolbar\",\"web-developer-options-toolbar\",\"customizableui-special-spring1\",\"web-developer-render-mode-statusbar\",\"web-developer-css-statusbar\",\"web-developer-javascript-statusbar\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[],\"dirtyAreaCache\":[\"toolbar-menubar\",\"nav-bar\",\"TabsToolbar\",\"web-developer-toolbar\",\"PersonalToolbar\"],\"currentVersion\":5,\"newElementCount\":1}");
user_pref("capability.policy.maonoscript.sites", "parrotsec.org cloudflare.com frozenbox.org duckduckgo.org about: about:addons about:blank about:blocked about:certerror about:config about:crashes about:home about:memory about:neterror about:plugins about:preferences about:privatebrowsing about:sessionrestore about:srcdoc about:support blob: chrome: http://cloudflare.com http://frozenbox.org http://parrotsec.org http://duckduckgo.org https://cloudflare.com https://frozenbox.org https://parrotsec.org https://duckduckgo.org mediasource: moz-extension: moz-safe-about: resource:");
user_pref("datareporting.healthreport.service.firstRun", false);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"useragentoverrider@qixinglu.com\":{\"version\":\"0.2.5.1-signed\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/extensions/useragentoverrider@qixinglu.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "https-everywhere-eff%40eff.org:5.1.1,%7B8f8fe09b-0bd3-4470-bc1b-8cad42b8203b%7D:0.17.1-signed,%7Ba0d7ccb3-214d-498b-b4aa-0e8fda9a7bf7%7D:20151208,%7B73a6fe31-595d-460b-a920-fcc0f8843232%7D:2.9.0.11,%7Bc45c406e-ab73-11d8-be73-000a95be3b12%7D:1.2.5");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.useragentoverrider.activated", false);
user_pref("extensions.useragentoverrider.currentLabel", "");
user_pref("extensions.useragentoverrider.entries", "# Linux\nLinux / Firefox 29: Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0\nLinux / Chrome 34: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/537.36\n\n# Mac\nMac / Firefox 29: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:29.0) Gecko/20100101 Firefox/29.0\nMac / Chrome 34: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/537.36\nMac / Safari 7: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/537.75.14\n\n# Windows\nWindows / Firefox 29: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:29.0) Gecko/20100101 Firefox/29.0\nWindows / Chrome 34: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/537.36\nWindows / IE 6: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)\nWindows / IE 7: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)\nWindows / IE 8: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0)\nWindows / IE 9: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)\nWindows / IE 10: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)\nWindows / IE 11: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko\n\n# Android\nAndroid / Firefox 29: Mozilla/5.0 (Android; Mobile; rv:29.0) Gecko/29.0 Firefox/29.0\nAndroid / Chrome 34: Mozilla/5.0 (Linux; Android 4.4.2; Nexus 4 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.114 Mobile Safari/537.36\n\n# iOS\niOS / Chrome 34: Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) CriOS/34.0.1847.18 Mobile/11B554a Safari/9537.53\niOS / Safari 7: Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53\n\n");
user_pref("extensions.useragentoverrider.firstRun", false);
user_pref("extensions.webdeveloper.version", "1.2");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1465342526000}},\"app-global\":{\"useragentoverrider@qixinglu.com\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/useragentoverrider@qixinglu.com.xpi\",\"e\":true,\"v\":\"0.2.5.1-signed\",\"st\":1469255661000}},\"app-system-share\":{\"https-everywhere-eff@eff.org\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/https-everywhere-eff@eff.org\",\"e\":true,\"v\":\"5.1.1\",\"st\":1467396983000,\"mt\":1385856000000},\"{8f8fe09b-0bd3-4470-bc1b-8cad42b8203b}\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{8f8fe09b-0bd3-4470-bc1b-8cad42b8203b}\",\"e\":true,\"v\":\"0.17.1-signed\",\"st\":1467396983000,\"mt\":1441037460000},\"{a0d7ccb3-214d-498b-b4aa-0e8fda9a7bf7}\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{a0d7ccb3-214d-498b-b4aa-0e8fda9a7bf7}\",\"e\":true,\"v\":\"20151208\",\"st\":1467396983000,\"mt\":1449610116000},\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{73a6fe31-595d-460b-a920-fcc0f8843232}\",\"e\":true,\"v\":\"2.9.0.11\",\"st\":1467396983000,\"mt\":1459959932000},\"{c45c406e-ab73-11d8-be73-000a95be3b12}\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{c45c406e-ab73-11d8-be73-000a95be3b12}\",\"e\":true,\"v\":\"1.2.5\",\"st\":1467396983000,\"mt\":1367235894000}}}");
user_pref("network.proxy.autoconfig_url", "file:///etc/tor/onion.pac");
user_pref("network.proxy.http", "127.0.0.1");
user_pref("network.proxy.http_port", 8080);
user_pref("network.proxy.socks", "127.0.0.1");
user_pref("network.proxy.socks_port", 9050);
user_pref("network.proxy.type", 2);
user_pref("noscript.ABE.migration", 1);
user_pref("noscript.gtemp", "");
user_pref("noscript.temp", "");
user_pref("noscript.visibleUIChecked", true);
user_pref("pref.advanced.proxies.disable_button.reload", false);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("pref.browser.homepage.disable_button.restore_default", false);
user_pref("pref.general.disable_button.default_browser", false);
user_pref("pref.privacy.disable_button.change_blocklist", false);
user_pref("pref.privacy.disable_button.view_cookies", false);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.key.menuAccessKeyFocuses", false);
pref("extensions.update.enabled", true);
pref("intl.locale.matchOS", true);
pref("browser.shell.checkDefaultBrowser", false);
pref("media.gmp-manager.url.override", "data:text/plain,");
pref("media.gmp-gmpopenh264.enabled", false);
pref("datareporting.healthreport.uploadEnabled", false);
