# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */
user_pref("network.dns.blockDotOnion", false);
user_pref("browser.startup.homepage","https://start.parrotsec.org");
user_pref("network.proxy.autoconfig_url", "file:///etc/anonsurf/onion.pac");
user_pref("network.proxy.socks", "127.0.0.1");
user_pref("network.proxy.socks_port", 9050);
user_pref("network.proxy.type", 2);
pref("extensions.update.enabled", true);
pref("intl.locale.matchOS", true);
pref("browser.shell.checkDefaultBrowser", false);
pref("media.gmp-manager.url.override", "data:text/plain,");
pref("media.gmp-gmpopenh264.enabled", false);
pref("datareporting.healthreport.uploadEnabled", false);
