etc/xdg/xfce4/terminal/*
usr/share/parrot-defaults/*
usr/share/applications/*
browser/00parrot.js etc/firefox-esr/
browser/00parrot.js etc/firefox/
browser/firefox.js etc/firefox-esr/
browser/firefox.js etc/firefox/
browser/00parrot.js usr/share/firefox-esr/browser/defaults/preferences/
browser/00parrot.js usr/share/firefox/browser/defaults/preferences/
browser/distribution.ini usr/share/firefox-esr/distribution/
browser/distribution.ini usr/share/firefox/distribution/
browser/policies.json usr/share/firefox-esr/distribution/
browser/policies.json usr/share/firefox/distribution/
browser/addons/privacy-badger-latest.xpi usr/share/firefox/distribution/extensions/jid1-MnnxcxisBPnSXQ-eff@jetpack.xpi
browser/addons/ublock_origin-1.26.2-an+fx.xpi usr/share/firefox/distribution/extensions/uBlock0@raymondhill.net.xpi
